[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NPM_CONFIG_REGISTRY = "https://registry.npmjs.org/"

# SPA fallback (safe even if you don't use a router)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200